# 注意: 部分内容由多位作者共同贡献，author 字段仅记录了第一位作者的链接。
course_name = "电路IA"
course_code = "EE1011A"

notices = """
本门课是选课制，有两个老师授课，所有电气、自动化学生从两个老师的课里任选，而不是传统的按班级划分。所以了解老师的授课风格很重要。
"""

[[lecturers]]
name = "王灿"
  [[lecturers.reviews]]
  content = """
授课风格：机电学院最好的老师之一，对于电路这门相对难懂的课，要把它讲好真的不容易。老师会用幻灯片，适当结合板书，对于题目的做法讲解细致。课前会用雨课堂推送预习题（计入平时成绩），课中也有现场做题，难度较大。
听课建议：选了他就好好听吧，这都不听算是亏大了。
"""
  author = { name = "Oliver Wu and Maxwell Jay", link = "https://github.com/OliverWu515", date = "2023-11-01" }

[[lecturers]]
name = "王毅"
  [[lecturers.reviews]]
  content = """
授课风格：车轱辘话比较多，总结能力较强，不强调做题细节，只点拨大致思路。
听课建议：听一个知识总结，掌握大致脉络还是足够的；但是对于做题的训练不够，所以课下需要多花时间。
"""
  author = { name = "Oliver Wu and Maxwell Jay", link = "https://github.com/OliverWu515", date = "2023-11-01" }

[[textbooks]]
title = "电路理论基础（第四版）"
book_author = "孙立山、陈希有等编著"
publisher = "高等教育出版社"
edition = "第四版"
type = "textbook"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "电路（第六版）"
book_author = "邱关源、罗先觉等编著"
publisher = "高等教育出版社"
edition = "第六版"
type = "reference"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "电路考研大串讲"
book_author = "孙立山等编著"
publisher = "科学出版社"
edition = ""
type = "reference"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "电路原理（第 2 版）"
book_author = "汪建等编著"
publisher = "清华大学出版社"
edition = "第 2 版"
type = "reference"
author = { name = "", link = "", date = "" }

[[textbooks]]
title = "Fundamentals of Electric Circuits(4th_Edition)"
book_author = "Charles K. Alexander, et al."
publisher = "McGraw-Hill"
edition = "4th Edition"
type = "reference"
author = { name = "", link = "", date = "" }

online_resources = []

[[course]]
content = """
两位老师的共同点：上课会讲很多难度不低的例题（基本来源于考研题）；均不考勤。
大家可以不局限于自己选的老师，而是可以都去听一听，感受一下哪个老师更适合自己，能够更好地理解知识点。
"""
author = { name = "Oliver Wu and Maxwell Jay", link = "https://github.com/OliverWu515", date = "2023-11-01" }

[[course]]
content = """
本课程主要学习《电路理论基础（第四版）》前 9 章。
主要内容包括：电路元件和电路基本定律、线性直流电路、电路定理、正弦稳态电路的相量分析、三相电路、非正弦周期电流电路、频率特性和谐振现象、线性动态电路暂态过程的时域分析、线性动态电路暂态过程的复频域分析。
个人建议学习顺序调整为：2.3 支路电流法；2.4 回路电流法；2.5 节点电压法；2.6-2.7 含运放电路的分析；2.1 电阻网络等效；3.1/2.2/3.3 含源支路和含源一端口等效；3.2 齐性定理、叠加定理；3.4-3.6 特勒根定理、互易定理、对偶原理。
预习时可将第六章提到第五章之前。
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2024-02-01" }

[[course]]
content = """
首先一定要结合例题消化基本概念，尤其注意前四章的学习（因为前四章大多是基本分析方法，相当于地基，地基不打牢，后续概念进一步增多，分析综合性加强的时候，就会跟不上了）。电路的前后章节联系相当紧密，一环扣一环，要注意同步跟进复习，切不可尝试速通，否则知识链条一旦断裂，补齐就会很困难。
课后题基本是考研题，难度较大，不过一定不要慌，也不要害怕，更不要对着答案抄。先将书本章节复习一下，然后才可开始做题。建议大家跟着上课进度做题，不要到章末做题。建议遇到题先独立思考，若不会则先去找书本对应章节，例题看懂、再理解后，再回来重看试题，若还是想不出来，再看此题答案，彻底理解答案思路后，再看下一道题。一定是先看书，后看题，再看答案，不要边看题边看着答案，这样容易以为自己都会。对于其中步骤，多问自己为什么，不要随便寻找拐棍。（说实话，考前很多同学自我感觉甚好，简单问一步是如何得出，却说不出所以然）做一遍后，复习两遍，至少可达到及格要求。从我观察来看，及格线边缘同学，基本分析方法都没有掌握，解题过程杂乱无章，基本公式形式都写不对。万勿掉进死做题的怪圈，靠着对知识模糊的“感觉”做很多题、或者看着答案做很多题、或者做了题但没订正没总结，都不算做题！
"""
author = { name = "Oliver Wu", link = "https://github.com/OliverWu515", date = "2024-02-01" }

[[course]]
content = """
这是一门非常重要的电学基础类课程，是三电（电路、模电、数电）的第一门，这门课的学习效果将直接影响到后续的学习，所以一定要认真对待。
在学习时一定要重视概念的理解以及知识点的总结，不能仅仅是为了做题而做题或者死记硬背，在有了自己对知识点的总结和提炼之后，再将这些运用到新的题目上，会发现做的更加得心应手。
「概念定理」、「做题方法」、「计算能力」这三者在这一门课中缺一不可，均需要花时间去练习或者总结。
- 对于「概念定理」，不仅仅是需要关注其内容，还需要关注其提出的背景、应用场景、适用条件、特殊情况的处理方式等等，这需要我们在学习、听讲以及自己做题的时候进行总结，这可能是一个比较复杂而无趣的过程，但是经过提炼和总结，概念定理可以更好地服务我们后续的学习以及做题。（这部分可能很抽象，可以多跟老师或者同学交流，也可以多看看学长学姐的笔记去理解）
- 「做题方法」的总结也是必要的，对于某些题目有特定的解题方案，这些方案可能是老师在课上讲解的，也可能是我们在做题的过程中总结出来的，这些方法的总结可以帮助我们在遇到类似题目的时候更快地解决问题。
- 「计算能力」包括笔算能力和卡西欧能力，二者缺一不可。我在考前就花了不少时间猛猛敲卡西欧）
个人认为王灿老师讲得不错，有启发意义，对于王毅老师的学生，也可以串门来听听，可以帮助更好地理解知识点。
附上我学习这门课时的笔记，供大家参考：位于 `notes` 文件夹下（打个广告，这是第八届学业支持类奖项哈工大（深圳）最美笔记奖的获奖笔记 awa）。
"""
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-09-01" }

[[exam]]
content = """
考试难度：较难。（22 届难度有所下降，估计有 30—40 人 90 分以上）
考试常常会出现大量中档题，就是每题都不难，但是每题都不那么直截了当，会设置些障碍，需要稍加思考才能得其本质。这就导致大家若是破题时间稍长，就容易做不完。不过考试题的题型绝大多数在作业题中出现过，所以作业题要会，而且要整理。不刻意整理，也要对基本概念、破题点有印象。

2023 年电信专业某班电路期末成绩：
| 总人数 | 60- | 60-70 | 70-80 | 80-90 | 90+ | 其他 | 平均分 | 最高分 | 最低分 |
| :----: | :-: | :---: | :---: | :---: | :-: | :--: | :----: | :----: | :----: |
|  148   | 23  |  55   |  30   |  22   | 16  |  2   | 67.19  |   97   |   8    |
"""
author = { name = "Oliver Wu and Maxwell Jay", link = "https://github.com/OliverWu515", date = "2023-11-01" }

lab = []

[[advice]]
content = """
1. 电路涉及很多复数运算和解方程，一定要熟练掌握科学计算器的使用。推荐型号 Casio 991CNX。
2. 想追求高分的可以尝试做做《考研大串讲》上的题目（难度均较大）（ps：大串讲上书后答案有较多错误）
3. 关于 Wang Can 老师平时分的建议：上课推的题尽量多多和群友室友交流（难度较大且限时）
4. 对于一般学生，考前做考研题没有必要，考试难度不会那么高。能够熟悉作业题足矣。
"""
author = { name = "Oliver Wu and Maxwell Jay", link = "https://github.com/OliverWu515", date = "2023-11-01" }

schedule = []

[[related_links]]
content = "卡西欧FX-991CNX计算器使用指南: https://hoa.moe/blog/how-to-use-fx991cn/"
author = { name = "psp_dada", link = "https://github.com/pspdada", date = "2024-09-01" }

misc = []